title: Daniel Herrera-Russert
font-family: "Arial", sans-serif
logo: /assets/img/headshot_circle.png
description: Master Architect (real estate, construction) and Data Science student
# show_downloads: true
theme: jekyll-theme-minimal
